# Generated by Django 5.0.2 on 2024-08-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveallocation',
            name='year',
            field=models.IntegerField(default=2024),
        ),
    ]
