# Generated by Django 5.0.2 on 2024-08-12 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0040_alter_salaryinfo_cc1_alter_salaryinfo_cc2_and_more'),
        ('leave', '0002_alter_leaveallocation_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leaveallocation',
            unique_together={('employee', 'leave_type', 'year')},
        ),
    ]
