# Generated by Django 5.0.2 on 2024-08-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0040_alter_salaryinfo_cc1_alter_salaryinfo_cc2_and_more'),
        ('leave', '0003_alter_leaveallocation_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leaveallocation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='leaveallocation',
            constraint=models.UniqueConstraint(fields=('employee', 'leave_type', 'year'), name='unique_leave_allocation'),
        ),
    ]
