# Generated by Django 5.0.2 on 2024-08-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0040_alter_salaryinfo_cc1_alter_salaryinfo_cc2_and_more'),
        ('leave', '0004_alter_leaveallocation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='leaveapplication',
            constraint=models.UniqueConstraint(fields=('employee', 'leave_type', 'start_date', 'end_date'), name='unique_leave_application'),
        ),
    ]
