# Generated by Django 5.0.2 on 2024-08-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_remove_leaveapplication_unique_leave_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
