# Generated by Django 5.0.2 on 2024-08-15 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_alter_holiday_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='leaveapplication',
            name='unique_leave_application',
        ),
    ]
