# Generated by Django 5.0.2 on 2024-08-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0040_alter_salaryinfo_cc1_alter_salaryinfo_cc2_and_more'),
        ('leave', '0008_remove_leaveapplication_unique_leave_application'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='leaveapplication',
            constraint=models.UniqueConstraint(fields=('employee', 'start_date', 'end_date'), name='unique_leave_application'),
        ),
    ]
