# Generated by Django 5.0.2 on 2024-04-07 05:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('unit', models.CharField(choices=[('Consumer', 'Consumer'), ('T.K. Food', 'T.K. Food')], max_length=255)),
                ('posting_date', models.DateField()),
                ('types', models.CharField(choices=[('Replacement', 'Replacement'), ('New', 'New')], max_length=255)),
                ('no_of_position', models.IntegerField()),
                ('filled_positions', models.PositiveIntegerField(default=0)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('open_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(default='Initial', max_length=255)),
                ('interview_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('interviewer', models.ManyToManyField(to='employees.employee')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
        ),
        migrations.CreateModel(
            name='FinalInterviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(default='Final', max_length=255)),
                ('interview_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('interviewer', models.TextField(default='')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
        ),
    ]
