# Generated by Django 5.0.2 on 2024-04-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalinterviewschedule',
            name='interviewer',
        ),
        migrations.AddField(
            model_name='finalinterviewschedule',
            name='interviewer',
            field=models.ManyToManyField(to='employees.employee'),
        ),
    ]
