# Generated by Django 5.0.2 on 2024-04-18 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_finalinterviewschedule_interviewer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='unit',
            field=models.CharField(choices=[('Consumer', 'Consumer'), ('T.K. Food', 'T.K. Food'), ('PPL', 'PPL'), ('PCL', 'PCL'), ('Glory', 'Glory')], max_length=255),
        ),
    ]
