# Generated by Django 5.0.2 on 2024-04-20 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='filled_positions',
        ),
    ]
