# Generated by Django 5.0.2 on 2024-05-03 12:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_job_filled_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalinterviewschedule',
            name='interview_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='interviewschedule',
            name='interview_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
