# Generated by Django 5.0.2 on 2024-05-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_finalinterviewschedule_interview_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='unit',
            field=models.CharField(choices=[('Consumer Division', 'Consumer'), ('T.K. Food Products Distribution Limited', 'T.K. Food'), ('Prime Pusti Limited', 'PPL'), ('Prime Cosmetics Limited', 'PCL'), ('Pusti Glory', 'Glory')], max_length=255),
        ),
    ]
