# Generated by Django 5.0.2 on 2024-05-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
