# Generated by Django 5.0.2 on 2024-05-13 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_remarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Remarks',
            new_name='remarks',
        ),
    ]
