# Generated by Django 5.0.2 on 2024-06-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_rename_remarks_job_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewschedule',
            name='job',
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='job',
            field=models.ManyToManyField(to='jobs.job'),
        ),
    ]
