# Generated by Django 5.0.2 on 2024-06-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_remove_interviewschedule_job_interviewschedule_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalinterviewschedule',
            name='job',
        ),
        migrations.AddField(
            model_name='finalinterviewschedule',
            name='job',
            field=models.ManyToManyField(to='jobs.job'),
        ),
    ]
