# Generated by Django 5.0.2 on 2024-06-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_remove_finalinterviewschedule_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
