# Generated by Django 5.0.2 on 2024-06-19 13:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_job_job_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalinterviewschedule',
            name='interview_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='interviewschedule',
            name='interview_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
