# Generated by Django 5.0.2 on 2024-09-19 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_alter_finalinterviewschedule_interview_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='unit',
            field=models.CharField(max_length=255),
        ),
    ]
