# Generated by Django 5.0.2 on 2024-09-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_alter_job_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='unit',
            field=models.CharField(choices=[('Consumer Division', 'Consumer'), ('T.K. Food Products Distribution Limited', 'T.K. Food'), ('Prime Pusti Limited', 'PPL'), ('Prime Cosmetics Limited', 'PCL'), ('Pusti Glory', 'Glory')], max_length=255),
        ),
    ]
