# Generated by Django 5.0.2 on 2024-09-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_alter_job_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='unit',
            field=models.CharField(choices=[('Consumer Division', 'Consumer Division'), ('T.K. Food Products Distribution Limited', 'T.K. Food Products Distribution Limited'), ('Prime Pusti Limited', 'Prime Pusti Limited'), ('Prime Cosmetics Limited', 'Prime Cosmetics Limited'), ('Pusti Glory', 'Pusti Glory')], max_length=255),
        ),
    ]
