# Generated by Django 5.0.2 on 2024-09-23 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_businessunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.businessunit'),
        ),
    ]
