# Generated by Django 5.0.2 on 2024-09-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_remove_job_business_unit_alter_job_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessunit',
            name='factory',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
