# Generated by Django 5.0.2 on 2024-09-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_businessunit_factory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessunit',
            name='factory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
