# Generated by Django 5.0.2 on 2024-04-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EID', models.CharField(blank=True, max_length=10, null=True, verbose_name='Employee ID')),
                ('name', models.CharField(max_length=60)),
                ('designation', models.CharField(max_length=60)),
                ('department', models.CharField(max_length=60)),
                ('DOJ', models.DateField(verbose_name='Date of Joining')),
                ('mobile_no', models.CharField(max_length=60, verbose_name='Mobile Number')),
                ('email', models.EmailField(max_length=60)),
                ('unit', models.CharField(max_length=60)),
            ],
        ),
    ]
