# Generated by Django 5.0.2 on 2024-04-07 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_contact_person', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_no', models.CharField(blank=True, max_length=20)),
                ('present_vill', models.CharField(blank=True, max_length=100)),
                ('present_po', models.CharField(blank=True, max_length=100)),
                ('present_ps', models.CharField(blank=True, max_length=100)),
                ('present_dist', models.CharField(blank=True, max_length=100)),
                ('permanent_vill', models.CharField(blank=True, max_length=100)),
                ('permanent_po', models.CharField(blank=True, max_length=100)),
                ('permanent_ps', models.CharField(blank=True, max_length=100)),
                ('permanent_dist', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('nid', models.CharField(blank=True, max_length=20)),
                ('tin', models.CharField(blank=True, max_length=20)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=10)),
                ('spouse_name', models.CharField(blank=True, max_length=100)),
                ('child', models.PositiveIntegerField(default=0)),
                ('father_name', models.CharField(blank=True, max_length=100)),
                ('mother_name', models.CharField(blank=True, max_length=100)),
                ('highest_degree', models.CharField(blank=True, max_length=100)),
                ('subject_highest_degree', models.CharField(blank=True, max_length=100)),
                ('institution_highest_degree', models.CharField(blank=True, max_length=100)),
                ('passing_year_highest_degree', models.PositiveIntegerField(blank=True, null=True)),
                ('division_or_gpa_highest_degree', models.CharField(blank=True, max_length=10)),
                ('professional_degree', models.CharField(blank=True, max_length=100)),
                ('subject_professional_degree', models.CharField(blank=True, max_length=100)),
                ('institution_professional_degree', models.CharField(blank=True, max_length=100)),
                ('passing_year_professional_degree', models.PositiveIntegerField(blank=True, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Employee Details',
                'verbose_name_plural': 'Employee Details',
            },
        ),
    ]
