# Generated by Django 5.0.2 on 2024-04-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_options_employeedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='EID',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Employee ID'),
        ),
    ]
