# Generated by Django 5.0.2 on 2024-04-24 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_eid'),
        ('jobs', '0004_remove_job_filled_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.job', verbose_name='Job'),
        ),
    ]
