# Generated by Django 5.0.2 on 2024-04-26 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employee_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='SeperationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resign_date', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seperation', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Separation Status',
                'verbose_name_plural': 'Separation Statuses',
            },
        ),
    ]
