# Generated by Django 5.0.2 on 2024-04-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee_active_status_seperationstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='EID',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='Employee ID'),
        ),
    ]
