# Generated by Django 5.0.2 on 2024-04-29 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0010_alter_offer_candidate'),
        ('employees', '0008_alter_employee_eid'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='candidate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidates.candidate'),
        ),
    ]
