# Generated by Django 5.0.2 on 2024-06-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_alter_employee_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominee_name', models.CharField(blank=True, max_length=100)),
                ('nominee_father_name', models.CharField(blank=True, max_length=100)),
                ('nominee_mohter_name', models.CharField(blank=True, max_length=100)),
                ('nominee_mobile_no', models.CharField(blank=True, max_length=100)),
                ('nominee_nid', models.CharField(blank=True, max_length=100)),
                ('nominee_vill', models.CharField(blank=True, max_length=100)),
                ('nominee_po', models.CharField(blank=True, max_length=100)),
                ('nominee_ps', models.CharField(blank=True, max_length=100)),
                ('nominee_dist', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='employeedetails',
            old_name='child',
            new_name='no_of_daughter',
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='emergency_person_address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='no_of_son',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='official_mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
