# Generated by Django 5.0.2 on 2024-06-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_nominee_rename_child_employeedetails_no_of_daughter_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nominee',
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='nominee_dist',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='nominee_father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='nominee_mobile_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='nominee_mohter_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='nominee_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='nominee_nid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='nominee_po',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='nominee_ps',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='nominee_vill',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
