# Generated by Django 5.0.2 on 2024-06-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_delete_nominee_employeedetails_nominee_dist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='no_of_daughter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='no_of_son',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='passing_year_highest_degree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='passing_year_professional_degree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
