# Generated by Django 5.0.2 on 2024-06-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_alter_employeedetails_no_of_daughter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='religion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
