# Generated by Django 5.0.2 on 2024-06-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_employeedetails_religion'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='relation_with_employee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
