# Generated by Django 5.0.2 on 2024-06-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_employeedetails_relation_with_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='marital_status',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
