# Generated by Django 5.0.2 on 2024-06-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_alter_employeedetails_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='emer_relation_with_employee',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
