# Generated by Django 5.0.2 on 2024-06-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_employeedetails_emer_relation_with_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='emer_relation_with_employee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
