# Generated by Django 5.0.2 on 2024-06-23 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_alter_employeedetails_emer_relation_with_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='confirmation_date',
            field=models.DateField(default=datetime.date(2024, 6, 23)),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_location',
            field=models.CharField(default='', max_length=255),
        ),
    ]
