# Generated by Django 5.0.2 on 2024-06-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_employee_confirmation_date_employee_job_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='confirmation_date',
            field=models.DateField(),
        ),
    ]
