# Generated by Django 5.0.2 on 2024-06-28 08:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0020_alter_employee_confirmation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(default=datetime.date(2024, 6, 28))),
                ('new_designation', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('Confirmation', 'Confirmation'), ('Extension', 'Extension')], max_length=100, null=True)),
                ('development_area', models.TextField(blank=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation', to='employees.employee')),
            ],
        ),
    ]
