# Generated by Django 5.0.2 on 2024-06-28 08:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0021_employeeconfirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeconfirmation',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
