# Generated by Django 5.0.2 on 2024-06-28 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0023_alter_employeeconfirmation_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeconfirmation',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation', to='employees.employee'),
        ),
    ]
