# Generated by Django 5.0.2 on 2024-06-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0025_alter_employeeconfirmation_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeconfirmation',
            name='effective_date',
            field=models.DateField(),
        ),
    ]
