# Generated by Django 5.0.2 on 2024-06-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0026_alter_employeeconfirmation_effective_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeconfirmation',
            name='status',
            field=models.CharField(choices=[('Confirmation', 'Confirmation'), ('Extension', 'Extension')], max_length=100),
        ),
    ]
