# Generated by Django 5.0.2 on 2024-07-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0027_alter_employeeconfirmation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeconfirmation',
            name='reference_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
