# Generated by Django 5.0.2 on 2024-07-02 07:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0028_employeeconfirmation_reference_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('new_job_location', models.CharField(max_length=100)),
                ('new_location_type', models.CharField(choices=[('region', 'Region'), ('zone', 'Zone')], max_length=100)),
                ('new_under_region_zone', models.CharField(blank=True, max_length=100, null=True)),
                ('new_under_region_zone_type', models.CharField(blank=True, choices=[('area', 'Area'), ('region', 'Region'), ('zone', 'Zone')], max_length=100, null=True)),
                ('report_to', models.CharField(max_length=255)),
                ('reference_number', models.IntegerField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='TransferOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('current_job_location', models.CharField(max_length=100)),
                ('current_location_type', models.CharField(choices=[('area', 'Area'), ('region', 'Region'), ('zone', 'Zone')], max_length=100)),
                ('current_under_region_zone', models.CharField(blank=True, max_length=100, null=True)),
                ('current_under_region_zone_type', models.CharField(choices=[('area', 'Area'), ('region', 'Region'), ('zone', 'Zone')], max_length=100)),
                ('new_job_location', models.CharField(max_length=100)),
                ('new_location_type', models.CharField(choices=[('region', 'Region'), ('zone', 'Zone')], max_length=100)),
                ('new_under_region_zone', models.CharField(blank=True, max_length=100, null=True)),
                ('new_under_region_zone_type', models.CharField(choices=[('area', 'Area'), ('region', 'Region'), ('zone', 'Zone')], max_length=100)),
                ('report_to', models.CharField(max_length=255)),
                ('reference_number', models.IntegerField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer', to='employees.employee')),
            ],
        ),
    ]
