# Generated by Django 5.0.2 on 2024-07-02 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0029_postingorder_transferorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='postingorder',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferorder',
            name='effective_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 2, 9, 35, 3, 279173, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postingorder',
            name='new_location_type',
            field=models.CharField(choices=[('area', 'Area'), ('region', 'Region'), ('zone', 'Zone')], max_length=100),
        ),
        migrations.AlterField(
            model_name='postingorder',
            name='new_under_region_zone_type',
            field=models.CharField(blank=True, choices=[('region', 'Region'), ('zone', 'Zone')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transferorder',
            name='current_under_region_zone_type',
            field=models.CharField(choices=[('region', 'Region'), ('zone', 'Zone')], max_length=100),
        ),
        migrations.AlterField(
            model_name='transferorder',
            name='new_location_type',
            field=models.CharField(choices=[('area', 'Area'), ('region', 'Region'), ('zone', 'Zone')], max_length=100),
        ),
        migrations.AlterField(
            model_name='transferorder',
            name='new_under_region_zone_type',
            field=models.CharField(choices=[('region', 'Region'), ('zone', 'Zone')], max_length=100),
        ),
    ]
