# Generated by Django 5.0.2 on 2024-07-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0030_postingorder_effective_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferorder',
            name='new_designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
