# Generated by Django 5.0.2 on 2024-07-06 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0031_transferorder_new_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='division_or_gpa_highest_degree',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='transferorder',
            name='current_under_region_zone_type',
            field=models.CharField(blank=True, choices=[('region', 'Region'), ('zone', 'Zone')], max_length=100),
        ),
        migrations.AlterField(
            model_name='transferorder',
            name='new_under_region_zone_type',
            field=models.CharField(blank=True, choices=[('region', 'Region'), ('zone', 'Zone')], max_length=100),
        ),
    ]
