# Generated by Django 5.0.2 on 2024-07-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0032_alter_employeedetails_division_or_gpa_highest_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='profile_picture',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
