# Generated by Django 5.0.2 on 2024-07-16 11:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0033_employeedetails_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('reference_number', models.IntegerField(blank=True, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
    ]
