# Generated by Django 5.0.2 on 2024-07-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0034_salaryinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryinfo',
            name='CC1',
            field=models.CharField(default='Director, Marketing', max_length=255),
        ),
        migrations.AddField(
            model_name='salaryinfo',
            name='CC2',
            field=models.CharField(default='Director, F & O', max_length=255),
        ),
        migrations.AddField(
            model_name='salaryinfo',
            name='CC3',
            field=models.CharField(default='Head of Business', max_length=255),
        ),
        migrations.AddField(
            model_name='salaryinfo',
            name='CC4',
            field=models.CharField(default='Accounts Department', max_length=255),
        ),
        migrations.AddField(
            model_name='salaryinfo',
            name='CC5',
            field=models.CharField(default='Personal file', max_length=255),
        ),
        migrations.AddField(
            model_name='salaryinfo',
            name='CC6',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salaryinfo',
            name='place_of_posting',
            field=models.CharField(default='Dhaka', max_length=255),
        ),
        migrations.AddField(
            model_name='salaryinfo',
            name='report_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
