# Generated by Django 5.0.2 on 2024-07-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0035_salaryinfo_cc1_salaryinfo_cc2_salaryinfo_cc3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryinfo',
            name='CC7',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
