# Generated by Django 5.0.2 on 2024-07-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0036_salaryinfo_cc7'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryinfo',
            name='director_signature',
            field=models.CharField(default='Director, Marketing', max_length=255),
        ),
    ]
