# Generated by Django 5.0.2 on 2024-07-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0037_salaryinfo_director_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryinfo',
            name='report_to',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='salaryinfo',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
