# Generated by Django 5.0.2 on 2024-07-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0038_alter_salaryinfo_report_to_alter_salaryinfo_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryinfo',
            name='CC4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salaryinfo',
            name='CC5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salaryinfo',
            name='CC6',
            field=models.CharField(default='Accounts Department', max_length=255),
        ),
        migrations.AlterField(
            model_name='salaryinfo',
            name='CC7',
            field=models.CharField(default='Personal file', max_length=255, null=True),
        ),
    ]
