# Generated by Django 5.0.2 on 2024-08-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0039_alter_salaryinfo_cc4_alter_salaryinfo_cc5_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryinfo',
            name='CC1',
            field=models.CharField(default='Business Director (Group-1)', max_length=255),
        ),
        migrations.AlterField(
            model_name='salaryinfo',
            name='CC2',
            field=models.CharField(default='Business Director (Group-2)', max_length=255),
        ),
        migrations.AlterField(
            model_name='salaryinfo',
            name='director_signature',
            field=models.CharField(default='Business Director (Group-1)', max_length=255),
        ),
    ]
