# Generated by Django 5.0.2 on 2024-09-24 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0040_alter_salaryinfo_cc1_alter_salaryinfo_cc2_and_more'),
        ('jobs', '0018_remove_job_business_unit_alter_job_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.businessunit'),
        ),
    ]
