# Generated by Django 5.0.2 on 2024-10-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0041_alter_employee_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryinfo',
            name='director_signature',
            field=models.CharField(blank=True, default='Business Director (Group-1)', max_length=255, null=True),
        ),
    ]
