# Generated by Django 5.0.2 on 2024-10-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0042_alter_salaryinfo_director_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postingorder',
            name='effective_date',
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name='postingorder',
            constraint=models.UniqueConstraint(fields=('employee', 'issue_date'), name='unique_posting_entry'),
        ),
        migrations.AddConstraint(
            model_name='transferorder',
            constraint=models.UniqueConstraint(fields=('employee', 'issue_date'), name='unique_transfer_entry'),
        ),
    ]
