# Generated by Django 5.0.2 on 2024-04-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('attendance_status', models.CharField(choices=[('Absent', 'Absent'), ('Present', 'Present')], default='absent', max_length=255)),
                ('invitation_status', models.CharField(blank=True, choices=[('Confirmed', 'Confirmed'), ('Not Interested', 'Not Interested'), ('Unable to Attend', 'Unable to Attend'), ('Call Not Received', 'Call Not Received'), ('Phone Switched Off', 'Phone Switched Off'), ('Interested in Next Schedule', 'Interested in Next Schedule'), ('Previously Interviewed', 'Previously Interviewed'), ('Wrong Number', 'Wrong Number')], default='Confirmed', max_length=255, null=True)),
                ('initial_interview_status', models.CharField(blank=True, choices=[('Deferred', 'Deferred'), ('Waiting', 'Waiting'), ('Forwarding for the next Interivew', 'Forwarding for the next Interivew'), ('immediate Recruitment', 'immediate Recruitment')], max_length=255, null=True)),
                ('final_interview_attendance', models.CharField(blank=True, choices=[('Absent', 'Absent'), ('Present', 'Present')], max_length=255, null=True)),
                ('final_interview_status', models.CharField(blank=True, choices=[('Deferred', 'Deferred'), ('Waiting', 'Waiting'), ('immediate Recruitment', 'immediate Recruitment')], max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_date', models.DateField(auto_now_add=True)),
                ('joining_date', models.DateField()),
                ('offer_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=255)),
                ('remarks', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
