# Generated by Django 5.0.2 on 2024-04-11 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatesDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_vill', models.CharField(blank=True, max_length=100)),
                ('present_po', models.CharField(blank=True, max_length=100)),
                ('present_ps', models.CharField(blank=True, max_length=100)),
                ('present_dist', models.CharField(blank=True, max_length=100)),
                ('permanent_vill', models.CharField(blank=True, max_length=100)),
                ('permanent_po', models.CharField(blank=True, max_length=100)),
                ('permanent_ps', models.CharField(blank=True, max_length=100)),
                ('permanent_dist', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('nid', models.CharField(blank=True, max_length=20)),
                ('tin', models.CharField(blank=True, max_length=20)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=10)),
                ('highest_degree', models.CharField(blank=True, max_length=100)),
                ('subject_highest_degree', models.CharField(blank=True, max_length=100)),
                ('institution_highest_degree', models.CharField(blank=True, max_length=100)),
                ('passing_year_highest_degree', models.PositiveIntegerField(blank=True, null=True)),
                ('division_or_gpa_highest_degree', models.CharField(blank=True, max_length=10)),
                ('professional_degree', models.CharField(blank=True, max_length=100)),
                ('subject_professional_degree', models.CharField(blank=True, max_length=100)),
                ('institution_professional_degree', models.CharField(blank=True, max_length=100)),
                ('passing_year_professional_degree', models.PositiveIntegerField(blank=True, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='candidates.candidate')),
            ],
            options={
                'verbose_name': 'Candidate Details',
                'verbose_name_plural': 'Candidate Details',
            },
        ),
    ]
