# Generated by Django 5.0.2 on 2024-04-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_candidatesdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatesdetails',
            old_name='employee',
            new_name='candidate',
        ),
        migrations.RemoveField(
            model_name='candidatesdetails',
            name='tin',
        ),
        migrations.AddField(
            model_name='candidatesdetails',
            name='current_designation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidatesdetails',
            name='current_organization',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidatesdetails',
            name='total_experience',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
