# Generated by Django 5.0.2 on 2024-04-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_rename_employee_candidatesdetails_candidate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatesdetails',
            name='passing_year_professional_degree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
