# Generated by Django 5.0.2 on 2024-04-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_alter_candidatesdetails_passing_year_highest_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatesdetails',
            name='degree_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
