# Generated by Django 5.0.2 on 2024-04-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_candidatesdetails_degree_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatesdetails',
            name='religion',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='candidatesdetails',
            name='marital_status',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
