# Generated by Django 5.0.2 on 2024-04-18 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_candidatesdetails_religion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatesdetails',
            name='division_or_gpa_highest_degree',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
