# Generated by Django 5.0.2 on 2024-04-24 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_alter_candidatesdetails_division_or_gpa_highest_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='candidates.candidate'),
        ),
    ]
