# Generated by Django 5.0.2 on 2024-05-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0010_alter_offer_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offered_designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
