# Generated by Django 5.0.2 on 2024-06-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0011_offer_offered_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
