# Generated by Django 5.0.2 on 2024-06-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0012_alter_offer_offer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='reference_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
