# Generated by Django 5.0.2 on 2024-06-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0013_offer_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='reference_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
