# Generated by Django 5.0.2 on 2024-06-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0014_alter_offer_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='reference_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
