# Generated by Django 5.0.2 on 2024-06-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0015_alter_offer_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
