# Generated by Django 5.0.2 on 2024-06-16 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0016_alter_offer_offer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 6, 16, 8, 49, 23, 951784, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
