# Generated by Django 5.0.2 on 2024-06-17 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0018_remove_candidate_job_candidate_job'),
        ('jobs', '0010_remove_finalinterviewschedule_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='jobs.job'),
        ),
    ]
