# Generated by Django 5.0.2 on 2024-06-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0019_offer_job'),
        ('jobs', '0010_remove_finalinterviewschedule_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='job',
            field=models.ManyToManyField(related_name='candidates', to='jobs.job'),
        ),
    ]
