# Generated by Django 5.0.2 on 2024-06-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0020_alter_candidate_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='attendance_status',
            field=models.CharField(choices=[('Absent', 'Absent'), ('Present', 'Present')], default='Absent', max_length=255),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='invitation_status',
            field=models.CharField(blank=True, choices=[('Confirmed', 'Confirmed'), ('Not Interested', 'Not Interested'), ('Unable to Attend', 'Unable to Attend'), ('Call Not Received', 'Call Not Received'), ('Phone Switched Off', 'Phone Switched Off'), ('Interested in Next Schedule', 'Interested in Next Schedule'), ('Previously Interviewed', 'Previously Interviewed'), ('Wrong Number', 'Wrong Number'), ('Salary Not Matched', 'Salary Not Matched')], default='Confirmed', max_length=255, null=True),
        ),
    ]
