# Generated by Django 5.0.2 on 2024-07-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0021_alter_candidate_attendance_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='final_interview_status',
            field=models.CharField(blank=True, choices=[('Deferred', 'Deferred'), ('Waiting', 'Waiting'), ('Immediate Recruitment', 'Immediate Recruitment')], max_length=255, null=True),
        ),
    ]
