# Generated by Django 5.0.2 on 2024-10-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0022_alter_candidate_final_interview_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatesdetails',
            name='professional_degree',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
