# Generated by Django 5.0.2 on 2024-10-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0023_alter_candidatesdetails_professional_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatesdetails',
            name='subject_professional_degree',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
